Fixed missing argument for args["ignore_quality_change"]
Fixed "TypeError: get() missing 1 required positional argument: 'option'" that occured when running the application.