Fix a bug while using merge sub-command directly While using merge directly, an error occurred in `_merge` function as below:
AttributeError: 'function' object has no attribute 'get_metadata_info' 
(line 225)

This is because `merge` is the function defined in 
livestream_saver/merge, not livestream_saver/merge itself.

By importing `get_metadata_info` from liverstream_saver/merge and 
invoking `merge` and `get_metadata_info` directly, the bug is fixed now.